export const getters = {
  PATIENT_LIST: "PATIENT_LIST",

  PHARMACY_LIST: "PHARMACY_LIST",

  QUERY_BAR_FILTER_DATA: "QUERY_BAR_FILTER_DATA",
  QUERY_BAR_LIST: "QUERY_BAR_FILTER_LIST",
};

export const actions = {
  PATIENT_LOAD_LIST: "PATIENT_LOAD_LIST",

  PHARMACY_LOAD_LIST: "PHARMACY_LOAD_LIST",

  QUERY_BAR_APPLY_FILTER: "QUERY_BAR_APPLY_FILTER",
  QUERY_BAR_RESET_FILTERS: "QUERY_BAR_RESET_FILTERS",
};

export const mutations = {
  PATIENT_SET_LIST: "PATIENT_SET_LIST",

  PHARMACY_SET_LIST: "PHARMACY_SET_LIST",

  QUERY_BAR_UPDATE_FILTER: "QUERY_BAR_UPDATE_FILTER",
  QUERY_BAR_RESET_FILTERS: "QUERY_BAR_RESET_FILTERS",
};
