CREATE TABLE Pharmacies (
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(100) NOT NULL,
	StateId TINYINT FOREIGN KEY REFERENCES States(Id),
	Address VARCHAR(100) NOT NULL,
	Email VARCHAR(100),
	Phone BIGINT
);
